spring:
  thymeleaf:
    cache: true
  profiles:
    active: prod
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: cn.liontalk.entity
  logging:
    config: classpath*:log4j2.xml
